import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { format } from 'date-fns'
import type { Booking } from '@/lib/supabase/queries/bookings'
import { CAMPING_GUEST_LIMIT, INCLUDED_RVS, INCLUDED_TENTS, MAX_RVS, nightlyCapacity, validateCampUnit, type CampUnit } from '@/lib/operations'
import { addCampUnit, addEmergencyContact, addVendorArrival, getBookingOperations, getInspectionPhotoUrl, removeCampUnit, removeEmergencyContact, removeVendorArrival, saveCabinStay, saveDamageDeposit, saveOpsProfile, updateCampUnit, updateOpsCheck, uploadInspectionPhoto, type InspectionPhoto, type OpsCheck } from '@/lib/supabase/queries/operations'

const card = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm'
const field = 'w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm'
const button = 'rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50'
const money = (cents: number) => new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(cents / 100)
const local = (value: string | null | undefined) => value ? format(new Date(value), "yyyy-MM-dd'T'HH:mm") : ''
const value = (form: FormData, key: string) => String(form.get(key) || '').trim()
const optional = (form: FormData, key: string) => value(form, key) || null
const cents = (form: FormData, key: string) => Math.round(Number(value(form, key) || 0) * 100)
const timestamp = (form: FormData, key: string) => value(form, key) ? new Date(value(form, key)).toISOString() : null

function PhotoLink({ photo }: { photo: InspectionPhoto }) {
  const { data, error } = useQuery({ queryKey: ['inspection-photo-url', photo.object_path], queryFn: () => getInspectionPhotoUrl(photo.object_path), staleTime: 45 * 60 * 1000 })
  return <li className="text-sm">{data ? <a className="text-blue-700 underline" href={data} target="_blank" rel="noreferrer">{photo.caption || 'Checkout photo'}</a> : error ? <span>Photo unavailable</span> : <span>Loading photo…</span>} · {new Date(photo.created_at).toLocaleString()}</li>
}

function CheckRow({ check, save, disabled }: { check: OpsCheck; save: (id: string, owner: string | null, notes: string | null, done: boolean) => Promise<void>; disabled: boolean }) {
  const [owner, setOwner] = useState(check.owner || '')
  const [notes, setNotes] = useState(check.notes || '')
  const [done, setDone] = useState(Boolean(check.completed_at))
  return <li className="rounded-md border p-3 text-sm">
    <div className="flex items-start gap-2"><input aria-label={`Complete ${check.label}`} type="checkbox" checked={done} onChange={event => setDone(event.target.checked)} /><span className="font-medium">{check.label}</span></div>
    <div className="mt-2 grid gap-2 sm:grid-cols-[1fr_2fr_auto]"><input aria-label={`${check.label} owner`} placeholder="Owner" value={owner} onChange={event => setOwner(event.target.value)} className={field} /><input aria-label={`${check.label} notes`} placeholder="Notes" value={notes} onChange={event => setNotes(event.target.value)} className={field} /><button type="button" disabled={disabled} onClick={() => void save(check.id, owner.trim() || null, notes.trim() || null, done)} className={button}>Save</button></div>
  </li>
}

export default function BookingOperations({ booking }: { booking: Booking }) {
  const client = useQueryClient()
  const { data, isLoading, error } = useQuery({ queryKey: ['booking-operations', booking.id], queryFn: () => getBookingOperations(booking.id) })
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [editingUnit, setEditingUnit] = useState<CampUnit | null>(null)
  const run = async (action: () => Promise<void>, form?: HTMLFormElement) => {
    setMessage(''); setBusy(true)
    try {
      await action()
      await client.invalidateQueries({ queryKey: ['booking-operations', booking.id] })
      await client.invalidateQueries({ queryKey: ['booking-workspace', booking.id] })
      await client.invalidateQueries({ queryKey: ['operations-sheet', booking.id] })
      await client.invalidateQueries({ queryKey: ['portal-operations', booking.id] })
      await client.invalidateQueries({ queryKey: ['dashboard-attention'] })
      form?.reset()
      setEditingUnit(null)
      setMessage('Saved.')
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Could not save changes.') }
    finally { setBusy(false) }
  }
  if (isLoading) return <section className={card}>Loading camping and operations…</section>
  if (error || !data) return <section role="alert" className={card}>Could not load camping and operations. Check your access and try again.</section>

  const nights = nightlyCapacity(booking.start_date, booking.end_date, data.camp)
  const submitUnit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const form = event.currentTarget, values = new FormData(form)
    const unit = {
      booking_id: booking.id,
      group_name: value(values, 'group_name'), kind: value(values, 'kind') as 'rv' | 'tent',
      unit_size_ft: optional(values, 'unit_size_ft') ? Number(value(values, 'unit_size_ft')) : null,
      occupants: Number(value(values, 'occupants')),
      arrival_on: value(values, 'arrival_on'), departure_on: value(values, 'departure_on'),
      contact_name: optional(values, 'contact_name'), contact_phone: optional(values, 'contact_phone'),
      site_label: optional(values, 'site_label'), notes: optional(values, 'notes'),
    }
    const validation = validateCampUnit(unit, booking.start_date, booking.end_date, data.camp.filter(row => row.id !== editingUnit?.id))
    if (validation) return setMessage(validation)
    void run(() => editingUnit ? updateCampUnit(editingUnit.id, unit) : addCampUnit(unit), form)
  }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-2xl font-bold">Camping and property operations</h2><p className="text-sm text-slate-600">Nightly register, readiness, vendors, weather, and checkout for this wedding.</p></div><Link className={button} to={`/admin/bookings/${booking.id}/operations-sheet`}>Print weekend sheet</Link></div>
    {message && <p role="status" className="rounded-md bg-slate-100 p-3 text-sm">{message}</p>}
    <section className={card}><h3 className="text-lg font-semibold">Nightly camping capacity</h3><p className="text-sm text-slate-600">Arrival is the first night; departure is checkout and does not count as a night. Up to {CAMPING_GUEST_LIMIT} campers and {MAX_RVS} RVs each night. {INCLUDED_RVS} RVs and {INCLUDED_TENTS} tents are included; extra units require contract review. The register does not calculate a fee.</p>
      <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Night</th><th className="p-2">Campers</th><th className="p-2">RVs</th><th className="p-2">Tents</th><th className="p-2">Allowance</th></tr></thead><tbody>{nights.map(day => <tr key={day.date} className="border-t"><td className="p-2">{day.date}</td><td className="p-2">{day.campers} / 60</td><td className="p-2">{day.rvs} / 15</td><td className="p-2">{day.tents}</td><td className="p-2">{day.extraRvs ? `${day.extraRvs} extra RV` : ''}{day.extraRvs && day.extraTents ? ', ' : ''}{day.extraTents ? `${day.extraTents} extra tent` : ''}{!day.extraRvs && !day.extraTents ? 'Within included units' : ''}</td></tr>)}</tbody></table></div>
      <ul className="my-4 space-y-2">{data.camp.map(unit => <li key={unit.id} className="rounded-md border p-3 text-sm"><strong>{unit.group_name}</strong> · {unit.kind.toUpperCase()}{unit.unit_size_ft ? ` · ${unit.unit_size_ft} ft` : ''} · {unit.occupants} people · {unit.arrival_on}–{unit.departure_on}{unit.site_label ? ` · site ${unit.site_label}` : ''}<div className="text-slate-600">{unit.contact_name || 'No contact'}{unit.contact_phone ? ` · ${unit.contact_phone}` : ''}{unit.notes ? ` · ${unit.notes}` : ''}</div><div className="mt-1 flex gap-3"><button type="button" className="text-blue-700 underline" onClick={() => setEditingUnit(unit)}>Edit</button><button type="button" className="text-red-700 underline" disabled={busy} onClick={() => void run(() => removeCampUnit(unit.id))}>Remove</button></div></li>)}</ul>
      <form key={editingUnit?.id || 'new'} onSubmit={submitUnit} className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input name="group_name" required maxLength={120} defaultValue={editingUnit?.group_name || ''} placeholder="Group or family name" className={field} /><select name="kind" defaultValue={editingUnit?.kind || 'tent'} className={field}><option value="tent">Tent</option><option value="rv">RV</option></select><input name="unit_size_ft" type="number" min="1" max="100" step="0.1" defaultValue={editingUnit?.unit_size_ft || ''} placeholder="Unit length (ft)" className={field} /><input name="occupants" type="number" required min="1" max="60" defaultValue={editingUnit?.occupants || ''} placeholder="Occupants" className={field} /><label className="text-sm">Arrival<input name="arrival_on" type="date" min={booking.start_date} max={booking.end_date} required defaultValue={editingUnit?.arrival_on || booking.start_date} className={field} /></label><label className="text-sm">Departure<input name="departure_on" type="date" min={booking.start_date} max={booking.end_date} required defaultValue={editingUnit?.departure_on || booking.end_date} className={field} /></label><input name="contact_name" defaultValue={editingUnit?.contact_name || ''} placeholder="Group contact" className={field} /><input name="contact_phone" defaultValue={editingUnit?.contact_phone || ''} placeholder="Contact phone" className={field} /><input name="site_label" defaultValue={editingUnit?.site_label || ''} placeholder="Site or area (optional)" className={field} /><input name="notes" defaultValue={editingUnit?.notes || ''} placeholder="Arrival notes" className={field} /><div className="flex items-end gap-2"><button disabled={busy} className={button}>{editingUnit ? 'Update group' : 'Add group'}</button>{editingUnit && <button type="button" onClick={() => setEditingUnit(null)} className="text-sm underline">Cancel</button>}</div></form>
    </section>
    <section className={card}><h3 className="text-lg font-semibold">Newlywed cabin</h3><p className="text-sm text-slate-600">Maximum four occupants. Record the actual stay separately from campsite totals.</p><form key={data.cabin?.booking_id || 'new'} onSubmit={event => { event.preventDefault(); const form = event.currentTarget, f = new FormData(form); void run(() => saveCabinStay({ booking_id: booking.id, guest_names: value(f, 'guest_names'), occupants: Number(value(f, 'occupants')), arrival_on: value(f, 'arrival_on'), departure_on: value(f, 'departure_on'), notes: optional(f, 'notes') })) }} className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input name="guest_names" required defaultValue={data.cabin?.guest_names || ''} placeholder="Cabin guests" className={field} /><input name="occupants" type="number" min="1" max="4" required defaultValue={data.cabin?.occupants || ''} placeholder="Occupants" className={field} /><label className="text-sm">Arrival<input name="arrival_on" type="date" min={booking.start_date} max={booking.end_date} required defaultValue={data.cabin?.arrival_on || booking.start_date} className={field} /></label><label className="text-sm">Departure<input name="departure_on" type="date" min={booking.start_date} max={booking.end_date} required defaultValue={data.cabin?.departure_on || booking.end_date} className={field} /></label><input name="notes" defaultValue={data.cabin?.notes || ''} placeholder="Cabin notes" className={field} /><button disabled={busy} className={button}>Save cabin stay</button></form></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className={card}><h3 className="text-lg font-semibold">Vendor arrivals</h3><ul className="my-3 space-y-2 text-sm">{data.vendors.map(vendor => <li key={vendor.id} className="border-b pb-2"><strong>{vendor.vendor_name}</strong> · {vendor.service} · {new Date(vendor.arrival_at).toLocaleString()}{vendor.departure_at ? ` to ${new Date(vendor.departure_at).toLocaleString()}` : ''}<div>{vendor.contact_name || ''} {vendor.contact_phone || ''}{vendor.power_needs ? ` · Power: ${vendor.power_needs}` : ''}</div><button disabled={busy} onClick={() => void run(() => removeVendorArrival(vendor.id))} className="text-red-700 underline">Remove</button></li>)}</ul><form onSubmit={event => { event.preventDefault(); const form = event.currentTarget, f = new FormData(form); void run(() => addVendorArrival({ booking_id: booking.id, vendor_name: value(f, 'vendor_name'), service: value(f, 'service'), contact_name: optional(f, 'contact_name'), contact_phone: optional(f, 'contact_phone'), arrival_at: timestamp(f, 'arrival_at')!, departure_at: timestamp(f, 'departure_at'), power_needs: optional(f, 'power_needs'), notes: optional(f, 'notes') }), form) }} className="grid gap-2"><input name="vendor_name" required placeholder="Vendor or company" className={field} /><input name="service" required placeholder="Service" className={field} /><div className="grid gap-2 sm:grid-cols-2"><input name="contact_name" placeholder="Contact name" className={field} /><input name="contact_phone" placeholder="Phone" className={field} /></div><label className="text-sm">Arrival<input name="arrival_at" type="datetime-local" required className={field} /></label><label className="text-sm">Departure (optional)<input name="departure_at" type="datetime-local" className={field} /></label><input name="power_needs" placeholder="Electrical needs" className={field} /><input name="notes" placeholder="Access notes" className={field} /><button disabled={busy} className={button}>Add vendor</button></form></section>
      <section className={card}><h3 className="text-lg font-semibold">Emergency contacts</h3><ul className="my-3 space-y-2 text-sm">{data.contacts.map(contact => <li key={contact.id} className="border-b pb-2"><strong>{contact.name}</strong> · {contact.role} · <a href={`tel:${contact.phone}`} className="underline">{contact.phone}</a>{contact.notes ? ` · ${contact.notes}` : ''} <button disabled={busy} onClick={() => void run(() => removeEmergencyContact(contact.id))} className="text-red-700 underline">Remove</button></li>)}</ul><form onSubmit={event => { event.preventDefault(); const form = event.currentTarget, f = new FormData(form); void run(() => addEmergencyContact({ booking_id: booking.id, name: value(f, 'name'), role: value(f, 'role'), phone: value(f, 'phone'), notes: optional(f, 'notes') }), form) }} className="grid gap-2"><input name="name" required placeholder="Name" className={field} /><input name="role" required placeholder="Role or relationship" className={field} /><input name="phone" required type="tel" placeholder="Phone" className={field} /><input name="notes" placeholder="Notes" className={field} /><button disabled={busy} className={button}>Add emergency contact</button></form></section></div>
    <section className={card}><h3 className="text-lg font-semibold">Weather and checkout plan</h3><form key={data.profile?.updated_at || 'new'} onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void run(() => saveOpsProfile({ booking_id: booking.id, weather_forecast: optional(f, 'weather_forecast'), weather_plan: optional(f, 'weather_plan'), weather_decision: optional(f, 'weather_decision'), weather_decided_at: timestamp(f, 'weather_decided_at'), checkout_notes: optional(f, 'checkout_notes'), checkout_completed_at: timestamp(f, 'checkout_completed_at') })) }} className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">Forecast and risks<textarea name="weather_forecast" defaultValue={data.profile?.weather_forecast || ''} rows={3} className={field} /></label><label className="text-sm">Contingency plan<textarea name="weather_plan" defaultValue={data.profile?.weather_plan || ''} rows={3} className={field} /></label><label className="text-sm">Decision and owner<input name="weather_decision" defaultValue={data.profile?.weather_decision || ''} className={field} /></label><label className="text-sm">Decision made at<input name="weather_decided_at" type="datetime-local" defaultValue={local(data.profile?.weather_decided_at)} className={field} /></label><label className="text-sm">Checkout inspection notes<textarea name="checkout_notes" defaultValue={data.profile?.checkout_notes || ''} rows={3} className={field} /></label><label className="text-sm">Checkout completed at<input name="checkout_completed_at" type="datetime-local" defaultValue={local(data.profile?.checkout_completed_at)} className={field} /></label><button disabled={busy} className={button}>Save operations plan</button></form></section>
    <section className={card}><h3 className="text-lg font-semibold">Property readiness checklist</h3><div className="mt-3 grid gap-4 lg:grid-cols-3">{(['setup','readiness','checkout'] as const).map(area => <div key={area}><h4 className="mb-2 font-semibold capitalize">{area}</h4><ul className="space-y-2">{data.checks.filter(check => check.area === area).map(check => <CheckRow key={`${check.id}-${check.owner}-${check.notes}-${check.completed_at}`} check={check} disabled={busy} save={(id, owner, notes, done) => run(() => updateOpsCheck(id, { owner, notes, completed_at: done ? new Date().toISOString() : null }))} />)}</ul></div>)}</div></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className={card}><h3 className="text-lg font-semibold">Damage deposit</h3><p className="text-sm text-slate-600">Use the signed contract for the agreed amount. Record actual receipts, refunds, and any retained amount. This is a manual ledger.</p><form key={data.deposit?.updated_at || 'new'} onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void run(() => saveDamageDeposit({ booking_id: booking.id, agreed_cents: cents(f, 'agreed'), received_cents: cents(f, 'received'), received_at: timestamp(f, 'received_at'), refunded_cents: cents(f, 'refunded'), refunded_at: timestamp(f, 'refunded_at'), retained_cents: cents(f, 'retained'), notes: optional(f, 'notes') })) }} className="mt-3 grid gap-2 sm:grid-cols-2"><label className="text-sm">Agreed deposit CAD<input name="agreed" type="number" min="0" step="0.01" required defaultValue={data.deposit ? (data.deposit.agreed_cents / 100).toFixed(2) : ''} className={field} /></label><label className="text-sm">Received CAD<input name="received" type="number" min="0" step="0.01" defaultValue={data.deposit ? (data.deposit.received_cents / 100).toFixed(2) : '0'} className={field} /></label><label className="text-sm">Received at<input name="received_at" type="datetime-local" defaultValue={local(data.deposit?.received_at)} className={field} /></label><label className="text-sm">Refunded CAD<input name="refunded" type="number" min="0" step="0.01" defaultValue={data.deposit ? (data.deposit.refunded_cents / 100).toFixed(2) : '0'} className={field} /></label><label className="text-sm">Refunded at<input name="refunded_at" type="datetime-local" defaultValue={local(data.deposit?.refunded_at)} className={field} /></label><label className="text-sm">Retained CAD<input name="retained" type="number" min="0" step="0.01" defaultValue={data.deposit ? (data.deposit.retained_cents / 100).toFixed(2) : '0'} className={field} /></label><label className="text-sm sm:col-span-2">Reason or reconciliation notes<textarea name="notes" defaultValue={data.deposit?.notes || ''} className={field} /></label><div className="sm:col-span-2 text-sm">Unresolved balance: {money(data.deposit ? data.deposit.received_cents - data.deposit.refunded_cents - data.deposit.retained_cents : 0)}</div><button disabled={busy} className={button}>Save deposit record</button></form></section>
      <section className={card}><h3 className="text-lg font-semibold">Checkout inspection photos</h3><p className="text-sm text-slate-600">Private images; links expire after one hour. Upload only property condition photos relevant to the inspection.</p><ul className="my-3 space-y-2">{data.photos.map(photo => <PhotoLink key={photo.id} photo={photo} />)}</ul><form onSubmit={event => { event.preventDefault(); const form = event.currentTarget, f = new FormData(form), file = f.get('photo'); if (!(file instanceof File) || !file.size) return setMessage('Choose an image to upload.'); void run(() => uploadInspectionPhoto(booking.id, file, value(f, 'caption')), form) }} className="grid gap-2"><input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required className={field} /><input name="caption" placeholder="What does this photo show?" className={field} /><button disabled={busy} className={button}>Upload inspection photo</button></form></section></div>
  </div>
}
