import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getBookingById } from '@/lib/supabase/queries/bookings'
import { getInquiries } from '@/lib/supabase/queries/inquiries'
import { getBookingOperations } from '@/lib/supabase/queries/operations'
import { nightlyCapacity } from '@/lib/operations'

const section = 'rounded-lg border border-slate-300 p-4 print:break-inside-avoid'
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString('en-CA') : 'Not recorded'

export default function OperationsSheet() {
  const { id = '' } = useParams()
  const { data, isLoading, error } = useQuery({ queryKey: ['operations-sheet', id], enabled: Boolean(id), queryFn: async () => {
    const [booking, operations, inquiries] = await Promise.all([getBookingById(id), getBookingOperations(id), getInquiries()])
    return { booking, operations, inquiry: inquiries.find(item => item.id === booking.inquiry_id) }
  } })
  if (isLoading) return <p className="p-6">Loading operations sheet…</p>
  if (error || !data) return <p role="alert" className="p-6">Could not load this wedding’s operations sheet.</p>
  const { booking, operations: ops, inquiry } = data
  const nights = nightlyCapacity(booking.start_date, booking.end_date, ops.camp)
  return <article className="mx-auto max-w-5xl space-y-5 bg-white p-6 text-slate-900 print:max-w-none print:p-0">
    <div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide">Rustic Retreat · Wedding weekend</p><h1 className="text-3xl font-bold">{inquiry?.full_name || 'Wedding'}{inquiry?.partner_name ? ` & ${inquiry.partner_name}` : ''}</h1><p>{booking.start_date} through {booking.end_date} · {booking.package_terms?.name || booking.package.replaceAll('_', ' ')}</p><p className="text-sm">Reception {booking.guest_reception_count} · booked camping estimate {booking.guest_camping_count}</p></div><div className="flex gap-3 print:hidden"><Link to={`/admin/bookings/${id}`} className="underline">Back</Link><button type="button" onClick={() => window.print()} className="rounded-md bg-slate-900 px-4 py-2 text-white">Print</button></div></div>
    <section className={section}><h2 className="text-lg font-semibold">Nightly property count</h2><table className="mt-2 w-full text-left text-sm"><thead><tr><th>Night</th><th>Campers / 60</th><th>RVs / 15</th><th>Tents</th><th>Allowances to review</th></tr></thead><tbody>{nights.map(night => <tr key={night.date} className="border-t"><td>{night.date}</td><td>{night.campers}</td><td>{night.rvs}</td><td>{night.tents}</td><td>{night.extraRvs ? `${night.extraRvs} RV above 8 ` : ''}{night.extraTents ? `${night.extraTents} tent above 12` : ''}</td></tr>)}</tbody></table></section>
    <div className="grid gap-4 md:grid-cols-2"><section className={section}><h2 className="text-lg font-semibold">Camping groups</h2><ul className="mt-2 space-y-2 text-sm">{ops.camp.map(unit => <li key={unit.id}><strong>{unit.group_name}</strong> · {unit.kind.toUpperCase()} · {unit.occupants} guests · {unit.arrival_on}–{unit.departure_on}{unit.unit_size_ft ? ` · ${unit.unit_size_ft} ft` : ''}{unit.site_label ? ` · ${unit.site_label}` : ''}<br />{unit.contact_name || ''} {unit.contact_phone || ''}{unit.notes ? ` · ${unit.notes}` : ''}</li>)}</ul>{!ops.camp.length && <p className="text-sm">Register incomplete.</p>}</section><section className={section}><h2 className="text-lg font-semibold">Cabin</h2>{ops.cabin ? <p className="text-sm">{ops.cabin.guest_names} · {ops.cabin.occupants} guests · {ops.cabin.arrival_on}–{ops.cabin.departure_on}{ops.cabin.notes ? ` · ${ops.cabin.notes}` : ''}</p> : <p className="text-sm">Cabin stay not recorded.</p>}</section></div>
    <section className={section}><h2 className="text-lg font-semibold">Vendor arrivals and power</h2><ul className="mt-2 space-y-2 text-sm">{ops.vendors.map(vendor => <li key={vendor.id}><strong>{vendor.vendor_name}</strong> · {vendor.service} · arrives {dateTime(vendor.arrival_at)}{vendor.departure_at ? ` · leaves ${dateTime(vendor.departure_at)}` : ''} · {vendor.contact_name || ''} {vendor.contact_phone || ''}{vendor.power_needs ? ` · Power: ${vendor.power_needs}` : ''}{vendor.notes ? ` · ${vendor.notes}` : ''}</li>)}</ul>{!ops.vendors.length && <p className="text-sm">No vendors recorded.</p>}</section>
    <div className="grid gap-4 md:grid-cols-2"><section className={section}><h2 className="text-lg font-semibold">Weather decision</h2><p className="text-sm">Forecast: {ops.profile?.weather_forecast || 'Not recorded'}</p><p className="text-sm">Plan: {ops.profile?.weather_plan || 'Not recorded'}</p><p className="text-sm">Decision: {ops.profile?.weather_decision || 'Pending'} · {dateTime(ops.profile?.weather_decided_at || null)}</p></section><section className={section}><h2 className="text-lg font-semibold">Emergency contacts</h2><ul className="mt-2 space-y-1 text-sm">{ops.contacts.map(contact => <li key={contact.id}>{contact.name} · {contact.role} · {contact.phone}{contact.notes ? ` · ${contact.notes}` : ''}</li>)}</ul>{!ops.contacts.length && <p className="text-sm">No contacts recorded.</p>}</section></div>
    <section className={section}><h2 className="text-lg font-semibold">Readiness and checkout</h2><div className="mt-2 grid gap-4 md:grid-cols-3">{(['setup','readiness','checkout'] as const).map(area => <div key={area}><h3 className="font-semibold capitalize">{area}</h3><ul className="space-y-1 text-sm">{ops.checks.filter(check => check.area === area).map(check => <li key={check.id}>{check.completed_at ? '☑' : '☐'} {check.label}{check.owner ? ` · ${check.owner}` : ''}{check.notes ? ` · ${check.notes}` : ''}</li>)}</ul></div>)}</div><p className="mt-3 text-sm">Checkout inspection: {dateTime(ops.profile?.checkout_completed_at || null)} · {ops.profile?.checkout_notes || 'No notes'}</p><p className="text-sm">Inspection photos: {ops.photos.length} stored privately in CRM.</p></section>
    <p className="text-xs text-slate-500">Prepared {new Date().toLocaleString('en-CA')}. Verify changes in the live CRM before use. This sheet contains private guest and vendor contact information.</p>
  </article>
}
